logdir: ./log/log_timit_base
dataset_root_dir: ./data/timit_norm_pkl
labeled_set: train
dev_set: dev
test_set: test
max_feature_length: 780
min_feature_length: 90
max_text_length: 80
min_text_length: 15
max_dec_timesteps: 85
batch_size: 40
shuffle: True
ls_weight: 0.05
input_dim: 80
enc_hidden_dim: 200
enc_output_dim: 200
enc_n_layers: 4
subsample: [2, 1]
dropout_rate: 0.2
dec_hidden_dim: 200
att_dim: 200
conv_channels: 10
conv_kernel_size: 100
att_odim: 200
embedding_dim: 50
learning_rate: 0.0005
weight_decay: 0.0000001
max_grad_norm: 5
load_model_path: ./models/timit_base/timit_base_best
retrieve_learning_rate: 0.0005
load_optimizer: True
init_tf_rate: 1.0
tf_start_decay_epochs: 40
tf_rate_lowerbound: 1.0
tf_decay_epochs: 90
epochs: 500
add_gaussian: False
gaussian_epoch: 20
gaussian_std: 0.075
tag: timit
model_dir: ./models/timit_base
model_name: timit_base
vocab_path: ./data/timit_norm_pkl/vocab_dict.p
non_lang_syms_path: ./data/timit_norm_pkl/non_lang_syms.p
sample_num: 5
early_stop_start_epoch: 200
early_stop: 30
test_file_name: test/predict_timit_base
z_data_path: z_data/timit_base.p
